export const data = [
  {
    id: 1,
    title: 'Земляные работы',
    description: 'Разработка грунта, перемещение грунта, уплотнение грунта, искусственное закрепление грунтов и т.д.',
    previewSrc: '/zemlyanye-raboty.png',
    href: '/zemlyanye-raboty',
  },
  {
    id: 2,
    title: 'Кровельные работы',
    description: 'Проектирование крыши, подготовка основания, укладка гидроизоляции, утепление крыши, монтаж кровельного покрытия,становка дополнительных элементов и т.д.',
    previewSrc: '/krovelnye-raboty.png',
    href: '/krovelnye-raboty',
  },
  {
    id: 3,
    title: 'Демонтаж зданий',
    description: 'Частичный, полный, первичный, вторичный.',
    previewSrc: '/demontazh.png',
    href: '/demontazh-zdanij',
  },
  {
    id: 4,
    title: 'Отделочные работы',
    description: 'Покрасочные, облицовочные, художественно-декоративные и др.',
    previewSrc: '/otdelochnye-raboty.png',
    href: '/otdelochnye-raboty',
  },
  {
    id: 5,
    title: 'Фасадные работы',
    description: 'Ремонт фасада, утепление фасада, облицовка фасада, украшение фасада, реставрация фасада.',
    previewSrc: '/fasadnye-raboty.png',
    href: '/fasadnye-raboty',
  },
  {
    id: 6,
    title: 'Устройства инженерных систем',
    description: `Компоненты систем отопления, элементы систем водоснабжения и водоотведения,
                  устройства вентиляции и кондиционирования, компоненты систем газоснабжения,
                  устройства слаботочных сетей, элементы сетей сигнализации.`,
    previewSrc: '/montazh-inzhenernyh-sistem.png',
    href: '/ustrojstvo-inzhenernykh-sistem',
  },
  {
    id: 7,
    title: 'Монтаж металлических конструкций',
    description: 'Подготовка к монтажу, установка опорных элементов, сборка и соединение элементов, сварочные работы, антикоррозийная обработка, контроль качества.',
    previewSrc: '/montazh-metallicheskih-konstrukcij.png',
    href: '/montazh-metallicheskih-konstrukcij',
  },
  {
    id: 8,
    title: 'Монтаж промышленного оборудования',
    description: 'Подготовка, проверка техники, распаковка, сборка, перемещение на место установки, подключение и проверка.',
    previewSrc: '/montazh-promyshlennogo-oborudovaniya.png',
    href: '/montazh-promyshlennogo-oborudovaniya',
  },
  {
    id: 9,
    title: 'Электромонтаж под ключ',
    description: `Проектирование электросети, закупка материалов и оборудования,
                  монтаж скрытой и открытой электропроводки, установка электрощита и
                  распределительных коробок, подключение и настройка оборудования, тестирование и сдача системы.`,
    previewSrc: '/elektromontazh-pod-klyuch.png',
    href: '/elektromontazh-pod-klyuch',
  },
  {
    id: 10 ,
    title: 'Строительство',
    description: 'Проектирование, выбор и закупка материалов, строительно-монтажные работы, финальная приёмка.',
    previewSrc: '/stroitelstvo-zdanij-i-sooruzhenij.png',
    href: '/stroitelstvo',
  },
];
